/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:24:17 GMT 2016
 */

package lt.Shmup.Main.Graphics;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ImageWrapper_ESTest extends ImageWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1113), (-1));
      defaultImageWrapper0.setWidth(973);
      int int0 = defaultImageWrapper0.getWidth();
      assertEquals(973, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1113), (-1));
      int int0 = defaultImageWrapper0.getWidth();
      assertEquals(-1, defaultImageWrapper0.getHeight());
      assertEquals((-1113), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(1, 1, 1);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 1, 0);
      defaultImageWrapper0.getImage();
      assertEquals(0, defaultImageWrapper0.getHeight());
      assertEquals(1, defaultImageWrapper0.getWidth());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 2096);
      assertEquals(2096, defaultImageWrapper0.getHeight());
      
      defaultImageWrapper0.setHeight(0);
      int int0 = defaultImageWrapper0.getHeight();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1113), (-1));
      int int0 = defaultImageWrapper0.getHeight();
      assertEquals((-1), int0);
      assertEquals(-1113, defaultImageWrapper0.getWidth());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1113), (-1));
      defaultImageWrapper0.setHeight(0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertEquals(0, defaultImageWrapper1.getHeight());
      assertEquals(0, defaultImageWrapper0.getHeight());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 2096);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertEquals(0, defaultImageWrapper1.getWidth());
      assertEquals(2096, defaultImageWrapper0.getHeight());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 2096);
      int int0 = defaultImageWrapper0.getHeight();
      assertEquals(2096, int0);
      assertEquals(0, defaultImageWrapper0.getWidth());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 2096);
      defaultImageWrapper0.getImage();
      assertEquals(2096, defaultImageWrapper0.getHeight());
      assertEquals(0, defaultImageWrapper0.getWidth());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 2096);
      int int0 = defaultImageWrapper0.getWidth();
      assertEquals(0, int0);
      assertEquals(2096, defaultImageWrapper0.getHeight());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(1, 1, 1);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 1, 0);
      defaultImageWrapper0.setHeight((-2735));
      defaultImageWrapper0.clone();
      assertEquals(-2735, defaultImageWrapper0.getHeight());
  }
}
