/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:34:54 GMT 2016
 */

package lt.Shmup.Main.GameObject.ObjectHandlers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import lt.Shmup.Main.GameObject.CollisionFinder;
import lt.Shmup.Main.GameObject.ObjectHandlers.DefaultObjectHandler;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Visitor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultObjectHandler_ESTest extends DefaultObjectHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultObjectHandler defaultObjectHandler0 = new DefaultObjectHandler((CollisionFinder) null, (Visitor) null);
      defaultObjectHandler0.render((Graphics2D) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultObjectHandler defaultObjectHandler0 = new DefaultObjectHandler((CollisionFinder) null, (Visitor) null);
      CollisionFinder collisionFinder0 = defaultObjectHandler0.getCollisionFinder();
      assertNull(collisionFinder0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultObjectHandler defaultObjectHandler0 = new DefaultObjectHandler((CollisionFinder) null, (Visitor) null);
      // Undeclared exception!
      try { 
        defaultObjectHandler0.removeEntity((Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.ObjectHandlers.DefaultObjectHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultObjectHandler defaultObjectHandler0 = new DefaultObjectHandler((CollisionFinder) null, (Visitor) null);
      // Undeclared exception!
      try { 
        defaultObjectHandler0.addEntity((Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.ObjectHandlers.DefaultObjectHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultObjectHandler defaultObjectHandler0 = new DefaultObjectHandler((CollisionFinder) null, (Visitor) null);
      defaultObjectHandler0.update();
  }
}
