/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:19:40 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables.Behaviour;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Behaviour.RandomMovementBehaviour;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RandomMovementBehaviour_ESTest extends RandomMovementBehaviour_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom(873);
      RandomMovementBehaviour randomMovementBehaviour0 = new RandomMovementBehaviour((-116));
      Identifier identifier0 = Identifier.PlayerProjectile;
      Entity entity0 = new Entity(873, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, true);
      // Undeclared exception!
      try { 
        randomMovementBehaviour0.update(entity0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Behaviour.RandomMovementBehaviour", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RandomMovementBehaviour randomMovementBehaviour0 = new RandomMovementBehaviour(0);
      Identifier identifier0 = Identifier.PlayerProjectile;
      Entity entity0 = new Entity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) randomMovementBehaviour0, (Renderable) null, true);
      randomMovementBehaviour0.update(entity0);
      assertEquals(0, entity0.getLayerIndex());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      System.setCurrentTimeMillis((-1L));
      RandomMovementBehaviour randomMovementBehaviour0 = new RandomMovementBehaviour(5124);
      Identifier identifier0 = Identifier.EnemyProjectile;
      Entity entity0 = new Entity((-4403), identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) randomMovementBehaviour0, (Renderable) null, true);
      randomMovementBehaviour0.update(entity0);
      assertEquals(-4403, entity0.getLayerIndex());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RandomMovementBehaviour randomMovementBehaviour0 = new RandomMovementBehaviour(5124);
      RandomMovementBehaviour randomMovementBehaviour1 = (RandomMovementBehaviour)randomMovementBehaviour0.clone();
      assertNotSame(randomMovementBehaviour1, randomMovementBehaviour0);
  }
}
