/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:56:11 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables.Behaviour;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Components.Updateables.Behaviour.SpawnerBehaviour;
import lt.Shmup.Main.GameObject.Factories.Entity.EntityFactory;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpawnerBehaviour_ESTest extends SpawnerBehaviour_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SpawnerBehaviour spawnerBehaviour0 = new SpawnerBehaviour((EntityFactory) null, 2147483646, 2147483646);
      spawnerBehaviour0.update((Entity) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SpawnerBehaviour spawnerBehaviour0 = new SpawnerBehaviour((EntityFactory) null, 561, 561);
      // Undeclared exception!
      try { 
        spawnerBehaviour0.update((Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Behaviour.SpawnerBehaviour", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SpawnerBehaviour spawnerBehaviour0 = new SpawnerBehaviour((EntityFactory) null, 2147483646, (-2032));
      // Undeclared exception!
      try { 
        spawnerBehaviour0.update((Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Behaviour.SpawnerBehaviour", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SpawnerBehaviour spawnerBehaviour0 = new SpawnerBehaviour((EntityFactory) null, 2147483646, (-2032));
      SpawnerBehaviour spawnerBehaviour1 = (SpawnerBehaviour)spawnerBehaviour0.clone();
      assertNotSame(spawnerBehaviour1, spawnerBehaviour0);
  }
}
