/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:22:50 GMT 2016
 */

package lt.Shmup.Main.Command.CommandStores;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import lt.Shmup.Main.Command.CommandStores.HashMapCommandStore;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HashMapCommandStore_ESTest extends HashMapCommandStore_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMapCommandStore<Object> hashMapCommandStore0 = new HashMapCommandStore<Object>();
      LinkedList<Object> linkedList0 = hashMapCommandStore0.getCommand(0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashMapCommandStore<Object> hashMapCommandStore0 = new HashMapCommandStore<Object>();
      hashMapCommandStore0.addCommand(0, "YY,");
      LinkedList<Object> linkedList0 = hashMapCommandStore0.getCommand(0);
      assertEquals(1, linkedList0.size());
  }
}
