/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:40:30 GMT 2016
 */

package lt.Shmup.Main.GameObject.Builders.NullCreators;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Main.GameObject.Builders.NullCreators.DefaultNullCreator;
import lt.Shmup.Main.GameObject.Components.Renderables.NullRenderable;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Healths.NullHealth;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.NullMovement;
import lt.Shmup.Main.GameObject.Components.Updateables.NullUpdateable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultNullCreator_ESTest extends DefaultNullCreator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultNullCreator defaultNullCreator0 = new DefaultNullCreator();
      NullUpdateable nullUpdateable0 = (NullUpdateable)defaultNullCreator0.getUpdateable();
      assertNotNull(nullUpdateable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultNullCreator defaultNullCreator0 = new DefaultNullCreator();
      NullRenderable nullRenderable0 = (NullRenderable)defaultNullCreator0.getRenderable();
      assertNotNull(nullRenderable0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultNullCreator defaultNullCreator0 = new DefaultNullCreator();
      NullMovement nullMovement0 = (NullMovement)defaultNullCreator0.getMovement();
      assertEquals(0.0F, nullMovement0.getSpeedY(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultNullCreator defaultNullCreator0 = new DefaultNullCreator();
      NullHealth nullHealth0 = (NullHealth)defaultNullCreator0.getHealth();
      assertEquals(0, nullHealth0.getMaximumHealth());
  }
}
