/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:14:29 GMT 2016
 */

package lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactorys;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Builders.EntityBuilder;
import lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactorys.DefaultProjectileFactory;
import lt.Shmup.Main.GameObject.Factories.ImageWrapperFactory;
import lt.Shmup.Main.GameObject.Factories.RenderableFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultProjectileFactory_ESTest extends DefaultProjectileFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultProjectileFactory defaultProjectileFactory0 = null;
      try {
        defaultProjectileFactory0 = new DefaultProjectileFactory((RenderableFactory) null, (ImageWrapperFactory) null, (EntityBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactorys.DefaultProjectileFactory", e);
      }
  }
}
