/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:58:42 GMT 2016
 */

package lt.Shmup.Main.Graphics.TextCenterers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import javax.swing.DebugGraphics;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.Graphics.TextCenterers.DefaultTextCenterer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultTextCenterer_ESTest extends DefaultTextCenterer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DebugGraphics debugGraphics0 = new DebugGraphics();
      DefaultTextCenterer defaultTextCenterer0 = new DefaultTextCenterer();
      // Undeclared exception!
      try { 
        defaultTextCenterer0.createCenteredTextPosition(debugGraphics0, (Position) null, (Volume) null, "-w&\u0001Qt<.(K!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("javax.swing.DebugGraphics", e);
      }
  }
}
