/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:13:01 GMT 2016
 */

package lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatchers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.event.MouseEvent;
import lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatchers.DefaultMouseCommandDispatcher;
import lt.Shmup.Main.Command.CommandStore;
import lt.Shmup.Main.MouseCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultMouseCommandDispatcher_ESTest extends DefaultMouseCommandDispatcher_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultMouseCommandDispatcher defaultMouseCommandDispatcher0 = new DefaultMouseCommandDispatcher((CommandStore<MouseCommand>) null);
      // Undeclared exception!
      try { 
        defaultMouseCommandDispatcher0.dispatchCommand((-1014), (MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatchers.DefaultMouseCommandDispatcher", e);
      }
  }
}
