/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:45:39 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Renderables;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import lt.Shmup.Main.GameObject.Components.Renderables.HealthBarGraphics;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HealthBarGraphics_ESTest extends HealthBarGraphics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HealthBarGraphics healthBarGraphics0 = new HealthBarGraphics((Entity) null);
      HealthBarGraphics healthBarGraphics1 = (HealthBarGraphics)healthBarGraphics0.clone();
      assertNotSame(healthBarGraphics0, healthBarGraphics1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Identifier identifier0 = Identifier.Unidentified;
      Entity entity0 = new Entity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false);
      HealthBarGraphics healthBarGraphics0 = new HealthBarGraphics(entity0);
      // Undeclared exception!
      try { 
        healthBarGraphics0.render((Graphics2D) null, entity0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Renderables.HealthBarGraphics", e);
      }
  }
}
