/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:03:37 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Renderables;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Graphics2D;
import lt.Shmup.Main.GameObject.Components.Renderables.NullRenderable;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NullRenderable_ESTest extends NullRenderable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NullRenderable nullRenderable0 = new NullRenderable();
      NullRenderable nullRenderable1 = (NullRenderable)nullRenderable0.clone();
      assertSame(nullRenderable1, nullRenderable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NullRenderable nullRenderable0 = new NullRenderable();
      nullRenderable0.render((Graphics2D) null, (Entity) null);
  }
}
