/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:39:48 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Renderables;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import lt.Shmup.Main.GameObject.Components.Renderables.RotatingImageGraphics;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Positions.BasicPosition;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import lt.Shmup.Main.Graphics.ImageWrapper;
import lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sun.java2d.SunGraphics2D;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RotatingImageGraphics_ESTest extends RotatingImageGraphics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(4, 10, 4);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 1, 0);
      RotatingImageGraphics rotatingImageGraphics0 = new RotatingImageGraphics((ImageWrapper) defaultImageWrapper0, 2.0F);
      SunGraphics2D sunGraphics2D0 = (SunGraphics2D)bufferedImage0.createGraphics();
      BasicPosition basicPosition0 = new BasicPosition((float) 0, (float) 10);
      rotatingImageGraphics0.drawImage(sunGraphics2D0, bufferedImage0, basicPosition0);
      assertEquals(10, bufferedImage0.getTileHeight());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-262), (-262));
      RotatingImageGraphics rotatingImageGraphics0 = new RotatingImageGraphics((ImageWrapper) defaultImageWrapper0, (float) (-262));
      BasicPosition basicPosition0 = new BasicPosition((float) (-262), (float) (-262));
      // Undeclared exception!
      try { 
        rotatingImageGraphics0.drawImage((Graphics2D) null, (Image) null, basicPosition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Renderables.RotatingImageGraphics", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(4, 10, 4);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 1, 0);
      RotatingImageGraphics rotatingImageGraphics0 = new RotatingImageGraphics((ImageWrapper) defaultImageWrapper0, 2.0F);
      RotatingImageGraphics rotatingImageGraphics1 = (RotatingImageGraphics)rotatingImageGraphics0.clone();
      assertFalse(rotatingImageGraphics1.equals((Object)rotatingImageGraphics0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(4, 10, 4);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 1, 0);
      RotatingImageGraphics rotatingImageGraphics0 = new RotatingImageGraphics((ImageWrapper) defaultImageWrapper0, 2.0F);
      SunGraphics2D sunGraphics2D0 = (SunGraphics2D)bufferedImage0.createGraphics();
      BasicPosition basicPosition0 = new BasicPosition((float) 0, (float) 10);
      Identifier identifier0 = Identifier.Unidentified;
      Entity entity0 = new Entity(10, identifier0, (Position) basicPosition0, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) rotatingImageGraphics0, true);
      rotatingImageGraphics0.render(sunGraphics2D0, entity0);
      rotatingImageGraphics0.drawImage(sunGraphics2D0, bufferedImage0, basicPosition0);
      assertEquals(0, sunGraphics2D0.renderHint);
  }
}
