/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:41:14 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Renderables;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import lt.Shmup.Main.GameObject.Components.Renderables.ScrollingBackgroundGraphics;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.Graphics.ImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ScrollingBackgroundGraphics_ESTest extends ScrollingBackgroundGraphics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScrollingBackgroundGraphics scrollingBackgroundGraphics0 = new ScrollingBackgroundGraphics((ImageWrapper) null);
      ScrollingBackgroundGraphics scrollingBackgroundGraphics1 = (ScrollingBackgroundGraphics)scrollingBackgroundGraphics0.clone();
      assertNotSame(scrollingBackgroundGraphics0, scrollingBackgroundGraphics1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScrollingBackgroundGraphics scrollingBackgroundGraphics0 = new ScrollingBackgroundGraphics((ImageWrapper) null);
      // Undeclared exception!
      try { 
        scrollingBackgroundGraphics0.render((Graphics2D) null, (Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Renderables.ScrollingBackgroundGraphics", e);
      }
  }
}
