/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:50:16 GMT 2016
 */

package lt.Shmup.Main.Graphics.ImageReaders;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.Graphics.ImageReaders.DefaultImageReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultImageReader_ESTest extends DefaultImageReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultImageReader defaultImageReader0 = new DefaultImageReader();
      // Undeclared exception!
      try { 
        defaultImageReader0.readImage("ov[FHaaGcQ.SLd", (-9), (-9));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input == null!
         //
         assertThrownBy("javax.imageio.ImageIO", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultImageReader defaultImageReader0 = new DefaultImageReader();
      // Undeclared exception!
      try { 
        defaultImageReader0.readImage("", 0, 150);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageReaders.DefaultImageReader", e);
      }
  }
}
