/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:18:56 GMT 2016
 */

package lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactorys;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactorys.DefaultEnemyFactoryFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultEnemyFactoryFactory_ESTest extends DefaultEnemyFactoryFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultEnemyFactoryFactory defaultEnemyFactoryFactory0 = new DefaultEnemyFactoryFactory();
      // Undeclared exception!
      try { 
        defaultEnemyFactoryFactory0.getFactory((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactorys.DefaultEnemyFactoryFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultEnemyFactoryFactory defaultEnemyFactoryFactory0 = new DefaultEnemyFactoryFactory();
      // Undeclared exception!
      try { 
        defaultEnemyFactoryFactory0.getFactory("W'+I!~");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Enemy Factories of type W'+I!~ does not exist.
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactorys.DefaultEnemyFactoryFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultEnemyFactoryFactory defaultEnemyFactoryFactory0 = new DefaultEnemyFactoryFactory();
      // Undeclared exception!
      try { 
        defaultEnemyFactoryFactory0.getFactory("basic");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Implementation for interface lt.Shmup.Main.GameObject.Factories.RenderableFactory is not configured.
         //
         assertThrownBy("lt.Shmup.Container", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultEnemyFactoryFactory defaultEnemyFactoryFactory0 = new DefaultEnemyFactoryFactory();
      // Undeclared exception!
      try { 
        defaultEnemyFactoryFactory0.getFactory("random");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Implementation for interface lt.Shmup.Main.GameObject.Factories.RenderableFactory is not configured.
         //
         assertThrownBy("lt.Shmup.Container", e);
      }
  }
}
