/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:55:28 GMT 2016
 */

package lt.Shmup.Main.Graphics.ImageWrappers;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Image;
import lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultImageWrapper_ESTest extends DefaultImageWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 609, (-405));
      defaultImageWrapper0.setWidth((-405));
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertFalse(defaultImageWrapper1.equals((Object)defaultImageWrapper0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertFalse(defaultImageWrapper1.equals((Object)defaultImageWrapper0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 609, (-405));
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertFalse(defaultImageWrapper1.equals((Object)defaultImageWrapper0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 832, 832);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)defaultImageWrapper0.clone();
      assertNotSame(defaultImageWrapper0, defaultImageWrapper1);
  }
}
