/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:37:04 GMT 2016
 */

package lt.Shmup.Main.Graphics.ImageWrappers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Color;
import java.awt.Image;
import lt.Shmup.Main.Graphics.ImageWrapper;
import lt.Shmup.Main.Graphics.ImageWrappers.Decorators.FlashingImageWrapperDecorator;
import lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ImageWrapperDecorator_ESTest extends ImageWrapperDecorator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1), (-1));
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (-1961.0F), 0.0F, (Color) null);
      defaultImageWrapper0.setWidth(0);
      int int0 = flashingImageWrapperDecorator0.getWidth();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 16, 16);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 16, (float) 16, (Color) null);
      int int0 = flashingImageWrapperDecorator0.getWidth();
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, 1995.3026F, 1995.3026F, (Color) null);
      ImageWrapper imageWrapper0 = flashingImageWrapperDecorator0.getImageWrapper();
      assertNull(imageWrapper0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, (-1));
      Color color0 = Color.lightGray;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 0, 703.6992F, color0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)flashingImageWrapperDecorator0.getImageWrapper();
      assertEquals(-1, defaultImageWrapper1.getHeight());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 603, 603);
      Color color0 = Color.CYAN;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, 0.0F, (-1941.4144F), color0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)flashingImageWrapperDecorator0.getImageWrapper();
      assertSame(defaultImageWrapper1, defaultImageWrapper0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1501), (-1501));
      Color color0 = Color.blue;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (-7.7321F), 0.0F, color0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)flashingImageWrapperDecorator0.getImageWrapper();
      assertEquals(-1501, defaultImageWrapper1.getHeight());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 16, 16);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 16, (float) 16, (Color) null);
      int int0 = flashingImageWrapperDecorator0.getHeight();
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 0);
      Color color0 = Color.getColor("", 637);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 0, (float) 0, color0);
      flashingImageWrapperDecorator0.setHeight((-284));
      int int0 = flashingImageWrapperDecorator0.getHeight();
      assertEquals((-284), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Color color0 = Color.darkGray;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, 1521.1F, (-1.0F), color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.setWidth(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageWrappers.ImageWrapperDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Color color0 = Color.BLACK;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, (-1.0F), (-1.0F), color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.setHeight(742);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageWrappers.ImageWrapperDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Color color0 = new Color(0, 0, 0);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, (-1.0F), (-1.0F), color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.getWidth();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageWrappers.ImageWrapperDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Color color0 = Color.getHSBColor((-1635.019F), (-1635.019F), 0.0F);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, 0.0F, 0.0F, color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.getHeight();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageWrappers.ImageWrapperDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 0);
      Color color0 = Color.getColor("", 637);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 0, (float) 0, color0);
      flashingImageWrapperDecorator0.setWidth(0);
      assertEquals(0, flashingImageWrapperDecorator0.getWidth());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-1), (-1));
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (-1961.0F), 0.0F, (Color) null);
      int int0 = flashingImageWrapperDecorator0.getWidth();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Color color0 = Color.darkGray;
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 0);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) (-1278), 173.32129F, color0);
      int int0 = flashingImageWrapperDecorator0.getHeight();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Color color0 = Color.GREEN;
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 1000, 0);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (-1.0F), 1.0F, color0);
      DefaultImageWrapper defaultImageWrapper1 = (DefaultImageWrapper)flashingImageWrapperDecorator0.getImageWrapper();
      assertSame(defaultImageWrapper0, defaultImageWrapper1);
  }
}
