/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:01:57 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables.Health.Healths;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Healths.NullHealth;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NullHealth_ESTest extends NullHealth_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NullHealth nullHealth0 = new NullHealth();
      nullHealth0.setHealth(276);
      NullHealth nullHealth1 = (NullHealth)nullHealth0.clone();
      assertEquals(276, nullHealth1.getHealth());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NullHealth nullHealth0 = new NullHealth();
      nullHealth0.setHealth((-291));
      NullHealth nullHealth1 = (NullHealth)nullHealth0.clone();
      assertEquals(0, nullHealth1.getMinimumHealth());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NullHealth nullHealth0 = new NullHealth();
      NullHealth nullHealth1 = (NullHealth)nullHealth0.clone();
      assertEquals(0, nullHealth1.getMaximumHealth());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NullHealth nullHealth0 = new NullHealth();
      nullHealth0.update((Entity) null);
      assertEquals(0, nullHealth0.getMaximumHealth());
  }
}
