/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:13:44 GMT 2016
 */

package lt.Shmup.Main.Input.KeyboardInputHandlers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.event.KeyEvent;
import lt.Shmup.Main.Command.Command;
import lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatcher;
import lt.Shmup.Main.Input.KeyState;
import lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultKeyboardInputHandler_ESTest extends DefaultKeyboardInputHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultKeyboardInputHandler defaultKeyboardInputHandler0 = new DefaultKeyboardInputHandler((KeyState) null, (KeyboardCommandDispatcher) null, (KeyboardCommandDispatcher) null);
      // Undeclared exception!
      try { 
        defaultKeyboardInputHandler0.addKeyPressedCommand(2216, (Command) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultKeyboardInputHandler defaultKeyboardInputHandler0 = new DefaultKeyboardInputHandler((KeyState) null, (KeyboardCommandDispatcher) null, (KeyboardCommandDispatcher) null);
      // Undeclared exception!
      try { 
        defaultKeyboardInputHandler0.keyReleased((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultKeyboardInputHandler defaultKeyboardInputHandler0 = new DefaultKeyboardInputHandler((KeyState) null, (KeyboardCommandDispatcher) null, (KeyboardCommandDispatcher) null);
      // Undeclared exception!
      try { 
        defaultKeyboardInputHandler0.addKeyReleasedCommand(18, (Command) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultKeyboardInputHandler defaultKeyboardInputHandler0 = new DefaultKeyboardInputHandler((KeyState) null, (KeyboardCommandDispatcher) null, (KeyboardCommandDispatcher) null);
      KeyState keyState0 = defaultKeyboardInputHandler0.getKeyStateContainer();
      assertNull(keyState0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultKeyboardInputHandler defaultKeyboardInputHandler0 = new DefaultKeyboardInputHandler((KeyState) null, (KeyboardCommandDispatcher) null, (KeyboardCommandDispatcher) null);
      // Undeclared exception!
      try { 
        defaultKeyboardInputHandler0.keyPressed((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler", e);
      }
  }
}
