/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:46:22 GMT 2016
 */

package lt.Shmup.Main.Input.Commands.Keyboard.Movement.Pressed;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.Input.Commands.Keyboard.Movement.Pressed.MovementVerticalCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovementVerticalCommand_ESTest extends MovementVerticalCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MovementVerticalCommand movementVerticalCommand0 = new MovementVerticalCommand((Entity) null, 1);
      // Undeclared exception!
      try { 
        movementVerticalCommand0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.Commands.Keyboard.Movement.Pressed.MovementVerticalCommand", e);
      }
  }
}
