/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:00:59 GMT 2016
 */

package lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatchers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.Command.Command;
import lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatchers.DefaultKeyboardCommandDispatcher;
import lt.Shmup.Main.Command.CommandStore;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultKeyboardCommandDispatcher_ESTest extends DefaultKeyboardCommandDispatcher_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultKeyboardCommandDispatcher defaultKeyboardCommandDispatcher0 = new DefaultKeyboardCommandDispatcher((CommandStore<Command>) null);
      // Undeclared exception!
      try { 
        defaultKeyboardCommandDispatcher0.dispatchCommand(2046);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatchers.DefaultKeyboardCommandDispatcher", e);
      }
  }
}
