/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:25:07 GMT 2016
 */

package lt.Shmup.Main.Graphics.ImageWrappers.Decorators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import lt.Shmup.Main.Graphics.ImageWrapper;
import lt.Shmup.Main.Graphics.ImageWrappers.Decorators.FlashingImageWrapperDecorator;
import lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FlashingImageWrapperDecorator_ESTest extends FlashingImageWrapperDecorator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 0, 0);
      Color color0 = Color.WHITE;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 0, (float) 0, color0);
      flashingImageWrapperDecorator0.clone();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(2, 2, 2);
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) bufferedImage0, 2253, 816);
      Color color0 = new Color(0, true);
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) 2, (float) 2253, color0);
      flashingImageWrapperDecorator0.clone();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-186), (-186));
      Color color0 = Color.black;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) (-186), (float) (-186), color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.getImage();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width (-186) and height (-186) cannot be <= 0
         //
         assertThrownBy("java.awt.image.DirectColorModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, (-186), (-186));
      Color color0 = Color.black;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (float) (-186), (float) (-186), color0);
      flashingImageWrapperDecorator0.clone();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Color color0 = Color.WHITE;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, (-3180.2F), 0.0F, color0);
      flashingImageWrapperDecorator0.resetAlpha();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultImageWrapper defaultImageWrapper0 = new DefaultImageWrapper((Image) null, 4088, 2633);
      Color color0 = Color.gray;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) defaultImageWrapper0, (-334.87158F), (-334.87158F), color0);
      BufferedImage bufferedImage0 = (BufferedImage)flashingImageWrapperDecorator0.getImage();
      assertEquals(2633, bufferedImage0.getHeight());
      assertEquals(4088, bufferedImage0.getWidth());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Color color0 = Color.white;
      FlashingImageWrapperDecorator flashingImageWrapperDecorator0 = new FlashingImageWrapperDecorator((ImageWrapper) null, 0.0F, (-1.0F), color0);
      // Undeclared exception!
      try { 
        flashingImageWrapperDecorator0.getImage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Graphics.ImageWrappers.Decorators.FlashingImageWrapperDecorator", e);
      }
  }
}
