/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:37:18 GMT 2016
 */

package lt.Shmup.Main.Input.Commands.Keyboard.Firing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import lt.Shmup.Main.Input.Commands.Keyboard.Firing.FirePressed;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FirePressed_ESTest extends FirePressed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FirePressed firePressed0 = new FirePressed((Entity) null);
      // Undeclared exception!
      try { 
        firePressed0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.Commands.Keyboard.Firing.FirePressed", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Identifier identifier0 = Identifier.EnemyProjectile;
      Entity entity0 = new Entity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false);
      FirePressed firePressed0 = new FirePressed(entity0);
      firePressed0.execute();
      firePressed0.execute();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Identifier identifier0 = Identifier.EnemyProjectile;
      Entity entity0 = new Entity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false);
      FirePressed firePressed0 = new FirePressed(entity0);
      firePressed0.setKeyPressed(false);
  }
}
