/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:05:52 GMT 2016
 */

package lt.Shmup.Main.Input.Commands.Mouse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.event.MouseEvent;
import lt.Shmup.Main.Command.Command;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.Input.Commands.Mouse.ButtonClickCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ButtonClickCommand_ESTest extends ButtonClickCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ButtonClickCommand buttonClickCommand0 = new ButtonClickCommand((Entity) null, (Command) null);
      // Undeclared exception!
      try { 
        buttonClickCommand0.execute((MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Input.Commands.Mouse.ButtonClickCommand", e);
      }
  }
}
