/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:53:56 GMT 2016
 */

package lt.Shmup.Main.Command;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatchers.DefaultMouseCommandDispatcher;
import lt.Shmup.Main.Command.CommandStore;
import lt.Shmup.Main.MouseCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandDispatcher_ESTest extends CommandDispatcher_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultMouseCommandDispatcher defaultMouseCommandDispatcher0 = new DefaultMouseCommandDispatcher((CommandStore<MouseCommand>) null);
      CommandStore<MouseCommand> commandStore0 = defaultMouseCommandDispatcher0.getCommandStore();
      assertNull(commandStore0);
  }
}
