/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:25:51 GMT 2016
 */

package lt.Shmup.Main.Input.Commands.Keyboard.Movement;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.Input.Commands.Keyboard.Movement.Pressed.MovementVerticalCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovementCommand_ESTest extends MovementCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MovementVerticalCommand movementVerticalCommand0 = new MovementVerticalCommand((Entity) null, 0);
      int int0 = movementVerticalCommand0.getSpeed();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MovementVerticalCommand movementVerticalCommand0 = new MovementVerticalCommand((Entity) null, 195);
      int int0 = movementVerticalCommand0.getSpeed();
      assertEquals(195, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MovementVerticalCommand movementVerticalCommand0 = new MovementVerticalCommand((Entity) null, 0);
      movementVerticalCommand0.getEntity();
      assertEquals(0, movementVerticalCommand0.getSpeed());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MovementVerticalCommand movementVerticalCommand0 = new MovementVerticalCommand((Entity) null, (-466));
      int int0 = movementVerticalCommand0.getSpeed();
      assertEquals((-466), int0);
  }
}
