/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:47:50 GMT 2016
 */

package lt.Shmup.Main.GameObject.Builders.EntityBuilders;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;
import lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder;
import lt.Shmup.Main.GameObject.Builders.NullCreator;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Entities.ButtonState;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultEntityBuilder_ESTest extends DefaultEntityBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setLayerIndex(1);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getDamageCausingEntity((-3689));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getEntity(2214);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.reset(5);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getTextEntity();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setText("a[ut7b");
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setHealth((Health) null);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getButtonEntity();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setLayerIndex(0);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setCollisionDamage(202);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setBehaviour((Updateable) null);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setPosition((Position) null);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setMovement((Movement) null);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setFont((Font) null);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getButtonEntity(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getTextEntity(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setIsCollidable(false);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.reset(1770);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setVolume((Volume) null);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setButtonStateColors((HashMap<ButtonState, Color>) null);
      assertSame(defaultEntityBuilder0, defaultEntityBuilder1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      Identifier identifier0 = Identifier.Enemy;
      defaultEntityBuilder0.setIdentifier(identifier0);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getDamageCausingEntity();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setRenderable((Renderable) null);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      DefaultEntityBuilder defaultEntityBuilder1 = (DefaultEntityBuilder)defaultEntityBuilder0.setColor((Color) null);
      assertSame(defaultEntityBuilder1, defaultEntityBuilder0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DefaultEntityBuilder defaultEntityBuilder0 = new DefaultEntityBuilder((NullCreator) null);
      // Undeclared exception!
      try { 
        defaultEntityBuilder0.getEntity();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder", e);
      }
  }
}
