/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:09:26 GMT 2016
 */

package lt.Shmup.Main.GameObject.Objects.Entities;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.util.LinkedList;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Objects.Components.EntityObserver;
import lt.Shmup.Main.GameObject.Objects.Entities.TextEntity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import lt.Shmup.Main.GameObject.Visitor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TextEntity_ESTest extends TextEntity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Identifier identifier0 = Identifier.Unidentified;
      TextEntity textEntity0 = new TextEntity((-3178), identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false, (LinkedList<EntityObserver>) null, "g?eqMxk/D5AR%.%", (Font) null, (Color) null);
      String string0 = textEntity0.getText();
      assertEquals("g?eqMxk/D5AR%.%", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Identifier identifier0 = Identifier.Enemy;
      TextEntity textEntity0 = new TextEntity(3205, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, true, (LinkedList<EntityObserver>) null, "", (Font) null, (Color) null);
      String string0 = textEntity0.getText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Identifier identifier0 = Identifier.EnemyProjectile;
      TextEntity textEntity0 = new TextEntity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, true, (LinkedList<EntityObserver>) null, "$VALUES", (Font) null, (Color) null);
      // Undeclared exception!
      try { 
        textEntity0.acceptRenderVisitor((Visitor) null, (Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Objects.Entities.TextEntity", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Identifier identifier0 = Identifier.PlayerProjectile;
      TextEntity textEntity0 = new TextEntity((-2404), identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false, (LinkedList<EntityObserver>) null, (String) null, (Font) null, (Color) null);
      String string0 = textEntity0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Identifier identifier0 = Identifier.EnemyProjectile;
      TextEntity textEntity0 = new TextEntity(0, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false, (LinkedList<EntityObserver>) null, "", (Font) null, (Color) null);
      textEntity0.setColor((Color) null);
      assertEquals(0, textEntity0.getLayerIndex());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Identifier identifier0 = Identifier.Player;
      TextEntity textEntity0 = new TextEntity((-3338), identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, false, (LinkedList<EntityObserver>) null, "M8E-", (Font) null, (Color) null);
      Font font0 = textEntity0.getFont();
      assertNull(font0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Identifier identifier0 = Identifier.Player;
      TextEntity textEntity0 = new TextEntity(2589, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, true, (LinkedList<EntityObserver>) null, "Mm", (Font) null, (Color) null);
      textEntity0.setText("Mm");
      assertTrue(textEntity0.isCollidable());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Identifier identifier0 = Identifier.EnemyProjectile;
      TextEntity textEntity0 = new TextEntity(1, identifier0, (Position) null, (Volume) null, (Health) null, (Movement) null, (Updateable) null, (Renderable) null, true, (LinkedList<EntityObserver>) null, "score", (Font) null, (Color) null);
      Color color0 = textEntity0.getColor();
      assertNull(color0);
  }
}
