/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:57:46 GMT 2016
 */

package lt.Shmup.Main.GameObject.Factories.RenderableFactorys;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Font;
import lt.Shmup.Main.GameObject.Components.Renderables.HealthBarGraphics;
import lt.Shmup.Main.GameObject.Components.Renderables.RotatingImageGraphics;
import lt.Shmup.Main.GameObject.Factories.ImageWrapperFactory;
import lt.Shmup.Main.GameObject.Factories.RenderableFactorys.DefaultRenderableFactory;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.Graphics.ImageWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultRenderableFactory_ESTest extends DefaultRenderableFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      defaultRenderableFactory0.getFont((-1694), 1614);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      defaultRenderableFactory0.getFont(3, (-2352));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      // Undeclared exception!
      try { 
        defaultRenderableFactory0.createBackgroundGraphics(":;!VAI/}9");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Config", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      defaultRenderableFactory0.createButtonStateColors();
      defaultRenderableFactory0.createButtonStateColors();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      defaultRenderableFactory0.createImageGraphics((ImageWrapper) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      // Undeclared exception!
      try { 
        defaultRenderableFactory0.createBackgroundGraphics((String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Given config path is invalid
         //
         assertThrownBy("lt.Shmup.Config", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      HealthBarGraphics healthBarGraphics0 = (HealthBarGraphics)defaultRenderableFactory0.createHealthBarGraphics((Entity) null);
      assertNotNull(healthBarGraphics0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      RotatingImageGraphics rotatingImageGraphics0 = (RotatingImageGraphics)defaultRenderableFactory0.createRotatingImageGraphics((ImageWrapper) null, 3);
      assertNotNull(rotatingImageGraphics0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DefaultRenderableFactory defaultRenderableFactory0 = new DefaultRenderableFactory((ImageWrapperFactory) null);
      Font font0 = defaultRenderableFactory0.getFont((-1123), 0);
      assertEquals(0.0F, font0.getSize2D(), 0.01F);
  }
}
