/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:27:16 GMT 2016
 */

package lt.Shmup.Main.GameObject.Objects.Components.EntityObservers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import lt.Shmup.Main.GameObject.Objects.Components.EntityObservers.ImageFlashObserver;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ImageFlashObserver_ESTest extends ImageFlashObserver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ImageFlashObserver imageFlashObserver0 = new ImageFlashObserver();
      // Undeclared exception!
      try { 
        imageFlashObserver0.notify((Entity) null, "damage_taken", (HashMap<String, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Objects.Components.EntityObservers.ImageFlashObserver", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ImageFlashObserver imageFlashObserver0 = new ImageFlashObserver();
      imageFlashObserver0.notify((Entity) null, "damage_raken", (HashMap<String, String>) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ImageFlashObserver imageFlashObserver0 = new ImageFlashObserver();
      ImageFlashObserver imageFlashObserver1 = (ImageFlashObserver)imageFlashObserver0.clone();
      assertFalse(imageFlashObserver1.equals((Object)imageFlashObserver0));
  }
}
