/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:15:11 GMT 2016
 */

package lt.Shmup.Main.GameObject.Objects.Components.EntityObservers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Objects.Components.EntityObservers.ProjectileSpawnObserver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ProjectileSpawnObserver_ESTest extends ProjectileSpawnObserver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProjectileSpawnObserver projectileSpawnObserver0 = null;
      try {
        projectileSpawnObserver0 = new ProjectileSpawnObserver();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Implementation for interface lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactory is not configured.
         //
         assertThrownBy("lt.Shmup.Container", e);
      }
  }
}
