/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:23:33 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Main.GameObject.Components.Updateables.NullUpdateable;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NullUpdateable_ESTest extends NullUpdateable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NullUpdateable nullUpdateable0 = new NullUpdateable();
      NullUpdateable nullUpdateable1 = (NullUpdateable)nullUpdateable0.clone();
      assertSame(nullUpdateable0, nullUpdateable1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NullUpdateable nullUpdateable0 = new NullUpdateable();
      nullUpdateable0.update((Entity) null);
  }
}
