/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:05:03 GMT 2016
 */

package lt.Shmup.Main.GameObject.CollisionFinders;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.CollisionFinders.DefaultCollisionFinder;
import lt.Shmup.Main.GameObject.Objects.Entity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultCollisionFinder_ESTest extends DefaultCollisionFinder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultCollisionFinder defaultCollisionFinder0 = new DefaultCollisionFinder();
      // Undeclared exception!
      try { 
        defaultCollisionFinder0.getCollidedEntities((Entity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.CollisionFinders.DefaultCollisionFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultCollisionFinder defaultCollisionFinder0 = new DefaultCollisionFinder();
      defaultCollisionFinder0.addEntity((Entity) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultCollisionFinder defaultCollisionFinder0 = new DefaultCollisionFinder();
      defaultCollisionFinder0.removeEntity((Entity) null);
  }
}
