/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:04:20 GMT 2016
 */

package lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Random;
import lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys.BasicEnemyFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BasicEnemyFactory_ESTest extends BasicEnemyFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom((-1609L));
      BasicEnemyFactory basicEnemyFactory0 = null;
      try {
        basicEnemyFactory0 = new BasicEnemyFactory((Random) mockRandom0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Implementation for interface lt.Shmup.Main.GameObject.Factories.RenderableFactory is not configured.
         //
         assertThrownBy("lt.Shmup.Container", e);
      }
  }
}
