/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:00:13 GMT 2016
 */

package lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys.RandomEnemyFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RandomEnemyFactory_ESTest extends RandomEnemyFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RandomEnemyFactory randomEnemyFactory0 = null;
      try {
        randomEnemyFactory0 = new RandomEnemyFactory(0, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Implementation for interface lt.Shmup.Main.GameObject.Factories.RenderableFactory is not configured.
         //
         assertThrownBy("lt.Shmup.Container", e);
      }
  }
}
