/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:02:54 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Components.State.Position;
import lt.Shmup.Main.GameObject.Components.State.Volume;
import lt.Shmup.Main.GameObject.Components.Updateables.Health.Health;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.LinearMovement;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ResetDecorator;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.NullMovement;
import lt.Shmup.Main.GameObject.Objects.Entity;
import lt.Shmup.Main.GameObject.Objects.Identifier;
import lt.Shmup.Main.GameObject.Renderable;
import lt.Shmup.Main.GameObject.Updateable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ResetDecorator_ESTest extends ResetDecorator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NullMovement nullMovement0 = new NullMovement();
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) nullMovement0);
      ResetDecorator resetDecorator1 = (ResetDecorator)resetDecorator0.clone();
      assertEquals(0.0F, resetDecorator1.getSpeedY(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinearMovement linearMovement0 = new LinearMovement(0.0F, (-1.0F));
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) linearMovement0);
      ResetDecorator resetDecorator1 = (ResetDecorator)resetDecorator0.clone();
      assertEquals(0.0F, resetDecorator1.getSpeedX(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinearMovement linearMovement0 = new LinearMovement((-1.0F), 67.379F);
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) linearMovement0);
      ResetDecorator resetDecorator1 = (ResetDecorator)resetDecorator0.clone();
      assertEquals((-1.0F), resetDecorator1.getSpeedX(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinearMovement linearMovement0 = new LinearMovement(2929.2944F, 2929.2944F);
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) linearMovement0);
      ResetDecorator resetDecorator1 = (ResetDecorator)resetDecorator0.clone();
      assertEquals(2929.2944F, resetDecorator1.getSpeedY(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NullMovement nullMovement0 = new NullMovement();
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) nullMovement0);
      Identifier identifier0 = Identifier.Unidentified;
      Entity entity0 = new Entity((-2971), identifier0, (Position) null, (Volume) null, (Health) null, (Movement) resetDecorator0, (Updateable) null, (Renderable) null, false);
      // Undeclared exception!
      try { 
        resetDecorator0.update(entity0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ResetDecorator", e);
      }
  }
}
