/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:56:54 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Renderables.TextRenderers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import lt.Shmup.Main.GameObject.Components.Renderables.TextRenderers.DefaultTextRenderer;
import lt.Shmup.Main.GameObject.Objects.Entities.TextEntity;
import lt.Shmup.Main.Graphics.TextCenterer;
import lt.Shmup.Main.Graphics.TextCenterers.DefaultTextCenterer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultTextRenderer_ESTest extends DefaultTextRenderer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultTextCenterer defaultTextCenterer0 = new DefaultTextCenterer();
      DefaultTextRenderer defaultTextRenderer0 = new DefaultTextRenderer((TextCenterer) defaultTextCenterer0);
      // Undeclared exception!
      try { 
        defaultTextRenderer0.render((Graphics2D) null, (TextEntity) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Renderables.TextRenderers.DefaultTextRenderer", e);
      }
  }
}
