/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:10:52 GMT 2016
 */

package lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ClampDecorator;
import lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ResetDecorator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovementDecorator_ESTest extends MovementDecorator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClampDecorator clampDecorator0 = new ClampDecorator((Movement) null);
      // Undeclared exception!
      try { 
        clampDecorator0.setSpeedY((-543.07996F));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResetDecorator resetDecorator0 = new ResetDecorator((Movement) null);
      // Undeclared exception!
      try { 
        resetDecorator0.getSpeedY();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClampDecorator clampDecorator0 = new ClampDecorator((Movement) null);
      // Undeclared exception!
      try { 
        clampDecorator0.getSpeedX();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ClampDecorator clampDecorator0 = new ClampDecorator((Movement) null);
      Movement movement0 = clampDecorator0.getMovement();
      assertNull(movement0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ClampDecorator clampDecorator0 = new ClampDecorator((Movement) null);
      // Undeclared exception!
      try { 
        clampDecorator0.setSpeedX(3384.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorator", e);
      }
  }
}
