/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:18:11 GMT 2016
 */

package lt.Shmup.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Logger;
import lt.Shmup.Main.ClassRegistrator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ClassRegistrator_ESTest extends ClassRegistrator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassRegistrator classRegistrator0 = new ClassRegistrator();
      classRegistrator0.createMainDependencies();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Logger.getInstance();
      Logger logger0 = Logger.getInstance();
      Logger.getInstance();
      ClassRegistrator classRegistrator0 = new ClassRegistrator();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      classRegistrator0.createMainDependencies();
      ClassRegistrator classRegistrator1 = new ClassRegistrator();
      ClassRegistrator classRegistrator2 = new ClassRegistrator();
      Logger.getInstance();
      ClassRegistrator classRegistrator3 = new ClassRegistrator();
      ClassRegistrator classRegistrator4 = new ClassRegistrator();
      classRegistrator2.createMainDependencies();
      classRegistrator2.createMainDependencies();
      ClassRegistrator classRegistrator5 = new ClassRegistrator();
      Logger logger1 = Logger.getInstance();
      assertSame(logger1, logger0);
  }
}
