/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:02:11 GMT 2016
 */

package lt.Shmup.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import lt.Shmup.Game;
import lt.Shmup.Main.Event;
import lt.Shmup.Main.Observer;
import lt.Shmup.Main.Observers.GameOverObserver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Event_ESTest extends Event_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameOverObserver gameOverObserver0 = new GameOverObserver((Game) null);
      Event.attachObserver(gameOverObserver0);
      Event.attachObserver(gameOverObserver0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameOverObserver gameOverObserver0 = new GameOverObserver((Game) null);
      Event.attachObserver(gameOverObserver0);
      Event.notify("Z&n|1KNA3 ^uk%6/", (HashMap<String, String>) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Event.attachObserver((Observer) null);
      // Undeclared exception!
      try { 
        Event.notify("", (HashMap<String, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Event", e);
      }
  }
}
