/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:54:45 GMT 2016
 */

package lt.Shmup.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import lt.Shmup.Game;
import lt.Shmup.Main.GameObject.ObjectHandler;
import lt.Shmup.Main.GameState;
import lt.Shmup.Main.Initializer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Initializer_ESTest extends Initializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Initializer initializer0 = new Initializer((Game) null);
      initializer0.initialize();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Game game0 = null;
      Initializer initializer0 = new Initializer((Game) null);
      initializer0.initialize();
      HashMap<GameState, ObjectHandler> hashMap0 = null;
      initializer0.setObjectHandlers(hashMap0);
      initializer0.setObjectHandlers(hashMap0);
      // Undeclared exception!
      try { 
        initializer0.createObjects();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Initializer", e);
      }
  }
}
