/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Nov 27 13:54:45 GMT 2016
 */

package lt.Shmup.Main;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Initializer_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "lt.Shmup.Main.Initializer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/usr/lib/jvm/java-8-openjdk-amd64/jre"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/home/lukas"); 
                                        java.lang.System.setProperty("user.dir", "/media/lukas/1A1A680A1A67E0ED/Stuff/KTU/4 Kursas/Patternai/shmup"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("line.separator", "\n"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Initializer_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.gson.internal.bind.TimeTypeAdapter$1",
      "lt.Shmup.Main.Graphics.ImageWrappers.ImageWrapperDecorator",
      "lt.Shmup.Config",
      "com.google.gson.internal.bind.JsonTreeWriter",
      "lt.Shmup.Main.GameObject.Builders.NullCreators.DefaultNullCreator",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "lt.Shmup.Main.GameObject.Factories.ImageWrapperFactory",
      "lt.Shmup.Main.GameObject.Objects.Components.EntityObserver",
      "lt.Shmup.Container",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.bind.TypeAdapters$35$1",
      "com.google.gson.internal.Excluder",
      "lt.Shmup.Main.Graphics.ImageReader",
      "com.google.gson.annotations.Until",
      "com.google.gson.internal.$Gson$Types$GenericArrayTypeImpl",
      "lt.Shmup.Main.Graphics.TextCenterer",
      "com.google.gson.stream.JsonReader$1",
      "com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter",
      "com.google.gson.internal.$Gson$Types",
      "lt.Shmup.Main.Input.MouseInputHandler",
      "lt.Shmup.Main.GameObject.Builders.NullCreator",
      "lt.Shmup.Main.Input.MouseInputHandlers.DefaultMouseInputHandler",
      "lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactory",
      "com.google.gson.JsonParser",
      "lt.Shmup.Game",
      "com.google.gson.Gson$FutureTypeAdapter",
      "com.google.gson.internal.bind.TreeTypeAdapter",
      "com.google.gson.stream.JsonWriter",
      "com.google.gson.internal.bind.ArrayTypeAdapter$1",
      "com.google.gson.internal.$Gson$Preconditions",
      "lt.Shmup.Main.Initializer",
      "lt.Shmup.Main.GameObject.Components.State.Position",
      "lt.Shmup.Main.GameObject.Factories.RenderableFactorys.DefaultRenderableFactory",
      "com.google.gson.stream.JsonToken",
      "com.google.gson.internal.ConstructorConstructor$3",
      "com.google.gson.internal.ObjectConstructor",
      "lt.Shmup.Main.Graphics.TextCenterers.DefaultTextCenterer",
      "com.google.gson.JsonNull",
      "lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactory",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatchers.DefaultKeyboardCommandDispatcher",
      "lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys.RandomEnemyFactory",
      "com.google.gson.JsonObject",
      "com.google.gson.internal.bind.JsonTreeReader$1",
      "com.google.gson.Gson$6",
      "com.google.gson.Gson$2",
      "com.google.gson.Gson$3",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.Gson$4",
      "com.google.gson.Gson$5",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ResetDecorator",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter",
      "lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactorys.BasicEnemyFactory",
      "com.google.gson.Gson$1",
      "lt.Shmup.Main.GameObject.Components.State.Volume",
      "com.google.gson.Gson",
      "com.google.gson.internal.LinkedTreeMap$1",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.OutOfBoundsDecorators.ReflectDecorator",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory",
      "lt.Shmup.Main.Observer",
      "lt.Shmup.Main.GameObject.Components.Updateables.Collision.HealthCollision",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory",
      "com.google.gson.internal.LinkedTreeMap$EntrySet",
      "lt.Shmup.Main.GameObject.Factories.ImageWrapperFactorys.DefaultImageWrapperFactory",
      "lt.Shmup.Main.GameObject.Factories.Entity.EntityFactory",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorator",
      "com.google.gson.internal.bind.TypeAdapters$2",
      "com.google.gson.internal.Excluder$1",
      "com.google.gson.internal.bind.TypeAdapters$1",
      "com.google.gson.JsonIOException",
      "com.google.gson.internal.bind.TypeAdapters$8",
      "com.google.gson.internal.bind.TypeAdapters$7",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.TypeAdapters$9",
      "com.google.gson.internal.bind.TypeAdapters$4",
      "com.google.gson.internal.bind.TypeAdapters$3",
      "com.google.gson.internal.bind.TypeAdapters$6",
      "com.google.gson.internal.bind.TypeAdapters$5",
      "lt.Shmup.Main.Input.KeyboardInputHandlers.DefaultKeyboardInputHandler",
      "lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatchers.DefaultMouseCommandDispatcher",
      "lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactorys.DefaultProjectileFactory",
      "com.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator",
      "lt.Shmup.Main.GameObject.Components.Renderables.TextRenderer",
      "lt.Shmup.Main.GameObject.Components.Updateables.Health.Health",
      "lt.Shmup.Main.ClassRegistrator",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory",
      "lt.Shmup.Main.GameObject.Factories.RenderableFactory",
      "com.google.gson.JsonPrimitive",
      "com.google.gson.internal.Streams$AppendableWriter",
      "lt.Shmup.Main.Input.KeyState",
      "lt.Shmup.Config$1",
      "lt.Shmup.Main.GameObject.Factories.Entity.EntityFactorys.DefaultEntityFactory",
      "com.google.gson.JsonSyntaxException",
      "lt.Shmup.Main.Input.KeyStates.HashMapKeyState",
      "lt.Shmup.Main.GameObject.ObjectHandler",
      "lt.Shmup.Main.Graphics.ImageWrapper",
      "com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl",
      "lt.Shmup.Main.GameObject.ObjectHandlers.DefaultObjectHandler",
      "com.google.gson.reflect.TypeToken",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.OutOfBoundsDecorator",
      "com.google.gson.internal.bind.TypeAdapters$23",
      "com.google.gson.internal.bind.TypeAdapters$24",
      "com.google.gson.internal.bind.TypeAdapters$25",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.Components.OutOfBoundsCheckers.DefaultOutOfBoundsChecker",
      "com.google.gson.internal.bind.TypeAdapters$26",
      "com.google.gson.internal.bind.TypeAdapters$20",
      "lt.Shmup.Main.Command.CommandDispatchers.KeyboardCommandDispatcher",
      "com.google.gson.TypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$21",
      "com.google.gson.internal.bind.TypeAdapters$22",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.internal.bind.TypeAdapters$28",
      "com.google.gson.FieldNamingStrategy",
      "com.google.gson.internal.bind.TypeAdapters$29",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper",
      "com.google.gson.ExclusionStrategy",
      "lt.Shmup.Main.GameObject.Renderable",
      "com.google.gson.internal.bind.TypeAdapters$34",
      "com.google.gson.internal.bind.TypeAdapters$35",
      "com.google.gson.internal.bind.TypeAdapters$36",
      "com.google.gson.internal.bind.TypeAdapters$30",
      "lt.Shmup.Main.GameObject.Components.Updateables.Health.Healths.DeathHealth",
      "lt.Shmup.Main.GameObject.Objects.Visitable",
      "com.google.gson.internal.bind.TypeAdapters$32",
      "com.google.gson.internal.bind.TypeAdapters$33",
      "com.google.gson.JsonArray",
      "com.google.gson.internal.LinkedTreeMap$EntrySet$1",
      "com.google.gson.TypeAdapterFactory",
      "com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movement",
      "lt.Shmup.Main.GameObject.Builders.EntityBuilders.DefaultEntityBuilder",
      "com.google.gson.stream.JsonReader",
      "lt.Shmup.Main.Graphics.ImageReaders.DefaultImageReader",
      "com.google.gson.internal.bind.MapTypeAdapterFactory",
      "lt.Shmup.Main.GameState",
      "com.google.gson.internal.LinkedTreeMap$Node",
      "lt.Shmup.Main.GameObject.Factories.Entity.ProjectileFactory",
      "com.google.gson.internal.Streams",
      "lt.Shmup.Main.Command.CommandDispatcher",
      "com.google.gson.internal.bind.TypeAdapters$12",
      "lt.Shmup.Main.Graphics.ImageWrappers.DefaultImageWrapper",
      "com.google.gson.internal.bind.TypeAdapters$13",
      "com.google.gson.internal.bind.TypeAdapters$14",
      "com.google.gson.internal.bind.TypeAdapters$15",
      "lt.Shmup.Main.GameObject.Components.Renderables.TextRenderers.DefaultTextRenderer",
      "com.google.gson.internal.bind.TypeAdapters$10",
      "lt.Shmup.Main.Input.KeyboardInputHandler",
      "com.google.gson.internal.bind.TypeAdapters$11",
      "lt.Shmup.Main.MouseCommand",
      "com.google.gson.stream.MalformedJsonException",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$16",
      "com.google.gson.internal.bind.TypeAdapters$17",
      "com.google.gson.internal.bind.TypeAdapters$18",
      "com.google.gson.internal.bind.TypeAdapters$19",
      "com.google.gson.internal.bind.DateTypeAdapter$1",
      "lt.Shmup.Main.GameObject.Components.Updateables.Health.Healths.NullHealth",
      "com.google.gson.TypeAdapter$1",
      "lt.Shmup.Main.Event",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$26$1",
      "lt.Shmup.Main.GameObject.CollisionFinders.DefaultCollisionFinder",
      "lt.Shmup.Main.GameObject.Visitors.DefaultVisitor",
      "lt.Shmup.Main.GameObject.Builders.EntityBuilder",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.ClampDecorator",
      "lt.Shmup.Main.Command.CommandDispatchers.MouseCommandDispatcher",
      "lt.Shmup.Main.GameObject.Objects.Entities.DamageCausingEntity",
      "lt.Shmup.Main.GameObject.Objects.Entities.ButtonState",
      "lt.Shmup.Main.Command.Command",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField",
      "lt.Shmup.Main.GameObject.Updateable",
      "lt.Shmup.Main.GameObject.Objects.Entities.TextEntity",
      "com.google.gson.internal.$Gson$Types$WildcardTypeImpl",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.internal.bind.SqlDateTypeAdapter$1",
      "com.google.gson.internal.LinkedTreeMap",
      "com.google.gson.internal.bind.ObjectTypeAdapter$2",
      "com.google.gson.internal.LazilyParsedNumber",
      "com.google.gson.internal.bind.ObjectTypeAdapter$1",
      "com.google.gson.JsonParseException",
      "com.google.gson.internal.ConstructorConstructor",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter",
      "lt.Shmup.Main.GameObject.Components.Updateables.Collision.HealthCollisions.DefaultHealthCollision",
      "com.google.gson.JsonElement",
      "lt.Shmup.Main.GameObject.Visitor",
      "lt.Shmup.Main.GameObject.Factories.Entity.EnemyFactoryFactorys.DefaultEnemyFactoryFactory",
      "lt.Shmup.Main.GameObject.Objects.Entity",
      "lt.Shmup.Main.Command.CommandStore",
      "lt.Shmup.Main.GameObject.Objects.Entities.ButtonEntity",
      "lt.Shmup.Main.Command.CommandStores.HashMapCommandStore",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$3",
      "lt.Shmup.Main.Graphics.ImageWrappers.Decorators.FlashingImageWrapperDecorator",
      "com.google.gson.annotations.Since",
      "com.google.gson.FieldNamingPolicy$5",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.LinearMovement",
      "com.google.gson.internal.JsonReaderInternalAccess",
      "lt.Shmup.Main.GameObject.CollisionFinder",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.MovementDecorators.Components.OutOfBoundsChecker",
      "lt.Shmup.Main.GameObject.Components.Updateables.Movement.Movements.NullMovement",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Initializer_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "lt.Shmup.Container",
      "lt.Shmup.Main.Event",
      "lt.Shmup.Main.GameState",
      "lt.Shmup.Config",
      "com.google.gson.internal.JsonReaderInternalAccess",
      "com.google.gson.stream.JsonReader",
      "com.google.gson.stream.JsonToken",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.TypeAdapters$36",
      "com.google.gson.internal.LinkedTreeMap",
      "com.google.gson.JsonPrimitive",
      "com.google.gson.internal.LazilyParsedNumber",
      "com.google.gson.internal.$Gson$Types",
      "com.google.gson.Gson",
      "com.google.gson.internal.Excluder",
      "com.google.gson.FieldNamingPolicy$1",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$3",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$5",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.internal.bind.ObjectTypeAdapter$2",
      "lt.Shmup.Main.GameObject.Objects.Entities.ButtonState"
    );
  }
}
