/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 13:38:00 GMT 2016
 */

package lt.Shmup.Main.Observers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import lt.Shmup.Game;
import lt.Shmup.Main.Observers.GameOverObserver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameOverObserver_ESTest extends GameOverObserver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameOverObserver gameOverObserver0 = new GameOverObserver((Game) null);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      // Undeclared exception!
      try { 
        gameOverObserver0.notify("player_destroyed", hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("lt.Shmup.Main.Observers.GameOverObserver", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameOverObserver gameOverObserver0 = new GameOverObserver((Game) null);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      gameOverObserver0.notify("playex_destroyed", hashMap0);
      assertEquals(0, hashMap0.size());
  }
}
