/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:28:04 GMT 2016
 */

package lt.Shmup;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Logger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Logger_ESTest extends Logger_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileSystemHandling.shouldAllThrowIOExceptions();
      Logger logger0 = Logger.getInstance();
      logger0.logException((Exception) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Logger logger0 = Logger.getInstance();
      logger0.log("`V)]|");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/logs/2014-02-14.log");
      byte[] byteArray0 = new byte[1];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      Logger.getInstance();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/logs");
      byte[] byteArray0 = new byte[1];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      Logger logger0 = Logger.getInstance();
      logger0.log("");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Logger logger0 = Logger.getInstance();
      Logger logger1 = Logger.getInstance();
      assertSame(logger1, logger0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/logs/2014-02-14.log");
      FileSystemHandling.createFolder(evoSuiteFile0);
      Logger logger0 = Logger.getInstance();
      assertNotNull(logger0);
  }
}
