/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 27 14:01:14 GMT 2016
 */

package lt.Shmup;

import org.junit.Test;
import static org.junit.Assert.*;
import lt.Shmup.Utility;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Utility_ESTest extends Utility_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      float float0 = Utility.clampFlt(0.0F, (-450.655F), 0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      float float0 = Utility.clampFlt(1949.79F, (-335.715F), (-247.206F));
      assertEquals((-247.206F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      float float0 = Utility.clampFlt((-1.0F), 2210.0F, 2980.0F);
      assertEquals(2210.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Utility utility0 = new Utility();
      assertEquals(1024, Utility.WINDOW_WIDTH);
  }
}
